"""initial schema

Revision ID: 1929cc0687cd
Revises: 
Create Date: 2025-11-12 18:34:46.803950

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1929cc0687cd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template_text", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompts_id"), ["id"], unique=False)

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_key"), ["key"], unique=True)

    op.create_table(
        "stock_ticker_map",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("gics_sector", sa.String(), nullable=True),
        sa.Column("gics_sub_industry", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )
    with op.batch_alter_table("stock_ticker_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_ticker_map_company_name"),
            ["company_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_ticker_map_gics_sector"), ["gics_sector"], unique=False
        )

    op.create_table(
        "target_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("target_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_target_accounts_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_target_accounts_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_target_accounts_username"), ["username"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("raw_json_response", sa.Text(), nullable=True),
        sa.Column("extracted_summary", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.Column("ai_model", sa.String(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("extracted_tickers", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_results_extracted_tickers"),
            ["extracted_tickers"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_results_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_results_prompt_id"), ["prompt_id"], unique=False
        )

    op.create_table(
        "collected_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("retweet_count", sa.Integer(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("link_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["username"],
            ["target_accounts.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collected_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collected_posts_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_collected_posts_post_id"), ["post_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_collected_posts_username"), ["username"], unique=False
        )

    op.create_table(
        "user_ticker_weights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("weight_ratio", sa.Float(), nullable=False),
        sa.Column("last_analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["target_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["stock_ticker_map.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "ticker", name="_account_ticker_uc"),
    )
    with op.batch_alter_table("user_ticker_weights", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_ticker_weights_account_id"),
            ["account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_ticker_weights_ticker"), ["ticker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_ticker_weights_weight_ratio"),
            ["weight_ratio"],
            unique=False,
        )

    op.create_table(
        "analysis_posts_link",
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("collected_post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collected_post_id"],
            ["collected_posts.id"],
        ),
        sa.PrimaryKeyConstraint("analysis_result_id", "collected_post_id"),
    )
    op.create_table(
        "ticker_sentiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("collected_post_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("sentiment", sa.String(length=10), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collected_post_id"],
            ["collected_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["stock_ticker_map.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ticker_sentiment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticker_sentiment_analysis_result_id"),
            ["analysis_result_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ticker_sentiment_collected_post_id"),
            ["collected_post_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ticker_sentiment_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ticker_sentiment_ticker"), ["ticker"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticker_sentiment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticker_sentiment_ticker"))
        batch_op.drop_index(batch_op.f("ix_ticker_sentiment_id"))
        batch_op.drop_index(batch_op.f("ix_ticker_sentiment_collected_post_id"))
        batch_op.drop_index(batch_op.f("ix_ticker_sentiment_analysis_result_id"))

    op.drop_table("ticker_sentiment")
    op.drop_table("analysis_posts_link")
    with op.batch_alter_table("user_ticker_weights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_ticker_weights_weight_ratio"))
        batch_op.drop_index(batch_op.f("ix_user_ticker_weights_ticker"))
        batch_op.drop_index(batch_op.f("ix_user_ticker_weights_account_id"))

    op.drop_table("user_ticker_weights")
    with op.batch_alter_table("collected_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collected_posts_username"))
        batch_op.drop_index(batch_op.f("ix_collected_posts_post_id"))
        batch_op.drop_index(batch_op.f("ix_collected_posts_id"))

    op.drop_table("collected_posts")
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_results_prompt_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_results_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_results_extracted_tickers"))

    op.drop_table("analysis_results")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("target_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_accounts_username"))
        batch_op.drop_index(batch_op.f("ix_target_accounts_provider"))
        batch_op.drop_index(batch_op.f("ix_target_accounts_id"))

    op.drop_table("target_accounts")
    with op.batch_alter_table("stock_ticker_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_ticker_map_gics_sector"))
        batch_op.drop_index(batch_op.f("ix_stock_ticker_map_company_name"))

    op.drop_table("stock_ticker_map")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_key"))

    op.drop_table("settings")
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompts_id"))

    op.drop_table("prompts")
    # ### end Alembic commands ###
