"""Create initial tables

Revision ID: 29560cbb1a00
Revises: 
Create Date: 2025-10-18 18:57:43.704393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29560cbb1a00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('processed_data', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collected_posts_id'), 'collected_posts', ['id'], unique=False)
    op.create_index(op.f('ix_collected_posts_post_id'), 'collected_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_collected_posts_username'), 'collected_posts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collected_posts_username'), table_name='collected_posts')
    op.drop_index(op.f('ix_collected_posts_post_id'), table_name='collected_posts')
    op.drop_index(op.f('ix_collected_posts_id'), table_name='collected_posts')
    op.drop_table('collected_posts')
    # ### end Alembic commands ###
