"""Create all tables

Revision ID: 4160013e2c9e
Revises: 
Create Date: 2025-10-24 23:19:44.996896

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4160013e2c9e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collected_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("retweet_count", sa.Integer(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("link_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collected_posts_id"), "collected_posts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_collected_posts_post_id"), "collected_posts", ["post_id"], unique=True
    )
    op.create_index(
        op.f("ix_collected_posts_username"),
        "collected_posts",
        ["username"],
        unique=False,
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template_text", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_prompts_id"), "prompts", ["id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=True)
    op.create_table(
        "target_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_accounts_id"), "target_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_target_accounts_username"),
        "target_accounts",
        ["username"],
        unique=True,
    )
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("raw_json_response", sa.Text(), nullable=True),
        sa.Column("extracted_summary", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_results_id"), "analysis_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_prompt_id"),
        "analysis_results",
        ["prompt_id"],
        unique=False,
    )
    op.create_table(
        "analysis_posts_link",
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("collected_post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collected_post_id"],
            ["collected_posts.id"],
        ),
        sa.PrimaryKeyConstraint("analysis_result_id", "collected_post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_posts_link")
    op.drop_index(op.f("ix_analysis_results_prompt_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_target_accounts_username"), table_name="target_accounts")
    op.drop_index(op.f("ix_target_accounts_id"), table_name="target_accounts")
    op.drop_table("target_accounts")
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_prompts_id"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_collected_posts_username"), table_name="collected_posts")
    op.drop_index(op.f("ix_collected_posts_post_id"), table_name="collected_posts")
    op.drop_index(op.f("ix_collected_posts_id"), table_name="collected_posts")
    op.drop_table("collected_posts")
    # ### end Alembic commands ###
