"""Add ai_model and cost_usd to AnalysisResult

Revision ID: 46dad2c35aec
Revises: 4160013e2c9e
Create Date: 2025-10-25 16:01:10.506925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46dad2c35aec"
down_revision: Union[str, Sequence[str], None] = "4160013e2c9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis_results", sa.Column("ai_model", sa.String(), nullable=True))
    op.add_column("analysis_results", sa.Column("cost_usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_results", "cost_usd")
    op.drop_column("analysis_results", "ai_model")
    # ### end Alembic commands ###
