"""Add extracted_tickers to AnalysisResult

Revision ID: 65bcd78985fe
Revises: cb9e51cfaf75
Create Date: 2025-11-06 17:00:15.049852

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "65bcd78985fe"
down_revision: Union[str, Sequence[str], None] = "cb9e51cfaf75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
