"""Rename processed_data to ai_summary

Revision ID: 69b11c5263c5
Revises: 29560cbb1a00
Create Date: 2025-10-18 19:06:30.309724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b11c5263c5'
down_revision: Union[str, Sequence[str], None] = '29560cbb1a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('collected_posts', sa.Column('ai_summary', sa.Text(), nullable=True))
    # op.drop_column('collected_posts', 'processed_data')
    op.alter_column('collected_posts', 'processed_data', new_column_name='ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('collected_posts', sa.Column('processed_data', sa.TEXT(), nullable=True))
    op.alter_column('collected_posts', 'ai_summary', new_column_name='processed_data')
    # ### end Alembic commands ###
