"""Final_Schema_Setup_Add_Sector_Remove_Aliases

Revision ID: 98ab5c1ef8be
Revises: 93f2a035a912
Create Date: 2025-11-06 19:52:22.550153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ab5c1ef8be'
down_revision: Union[str, Sequence[str], None] = '93f2a035a912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ticker_map', sa.Column('gics_sector', sa.String(), nullable=True))
    op.add_column('stock_ticker_map', sa.Column('gics_sub_industry', sa.String(), nullable=True))
    op.create_index(op.f('ix_stock_ticker_map_gics_sector'), 'stock_ticker_map', ['gics_sector'], unique=False)
    op.drop_column('stock_ticker_map', 'aliases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ticker_map', sa.Column('aliases', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stock_ticker_map_gics_sector'), table_name='stock_ticker_map')
    op.drop_column('stock_ticker_map', 'gics_sub_industry')
    op.drop_column('stock_ticker_map', 'gics_sector')
    # ### end Alembic commands ###
