"""Add provider column to target_accounts

Revision ID: c3c244e4539d
Revises: 89abeef2a6d7
Create Date: 2025-11-08 14:31:38.424488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c244e4539d'
down_revision: Union[str, Sequence[str], None] = '89abeef2a6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_accounts', sa.Column('provider', sa.String(length=20), nullable=False, server_default='X'))
    op.create_index(op.f('ix_target_accounts_provider'), 'target_accounts', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_accounts_provider'), table_name='target_accounts')
    op.drop_column('target_accounts', 'provider')
    # ### end Alembic commands ###
