"""Add input_tokens and output_tokens to AnalysisResult

Revision ID: cb9e51cfaf75
Revises: d4753ed70e9d
Create Date: 2025-10-29 14:31:10.578234

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb9e51cfaf75"
down_revision: Union[str, Sequence[str], None] = "d4753ed70e9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results", sa.Column("input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "analysis_results", sa.Column("output_tokens", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_results", "output_tokens")
    op.drop_column("analysis_results", "input_tokens")
    # ### end Alembic commands ###
