"""Add extracted_tickers to AnalysisResult

Revision ID: 87dc28e65bf4
Revises: 65bcd78985fe
Create Date: 2025-11-06 17:00:38.530160

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87dc28e65bf4"
down_revision: Union[str, Sequence[str], None] = "65bcd78985fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results", sa.Column("extracted_tickers", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_analysis_results_extracted_tickers"),
        "analysis_results",
        ["extracted_tickers"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analysis_results_extracted_tickers"), table_name="analysis_results"
    )
    op.drop_column("analysis_results", "extracted_tickers")
    # ### end Alembic commands ###
