"""Add StockTickerMap, TickerSentiment, and UserTickerWeight tables

Revision ID: 93f2a035a912
Revises: 87dc28e65bf4
Create Date: 2025-11-06 19:26:26.470866

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93f2a035a912"
down_revision: Union[str, Sequence[str], None] = "87dc28e65bf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_ticker_map",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("aliases", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index(
        op.f("ix_stock_ticker_map_company_name"),
        "stock_ticker_map",
        ["company_name"],
        unique=False,
    )
    op.create_table(
        "user_ticker_weights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("weight_ratio", sa.Float(), nullable=False),
        sa.Column("last_analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["target_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["stock_ticker_map.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "ticker", name="_account_ticker_uc"),
    )
    op.create_index(
        op.f("ix_user_ticker_weights_account_id"),
        "user_ticker_weights",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_ticker_weights_ticker"),
        "user_ticker_weights",
        ["ticker"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_ticker_weights_weight_ratio"),
        "user_ticker_weights",
        ["weight_ratio"],
        unique=False,
    )
    op.create_table(
        "ticker_sentiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("collected_post_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("sentiment", sa.String(length=10), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collected_post_id"],
            ["collected_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["stock_ticker_map.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticker_sentiment_analysis_result_id"),
        "ticker_sentiment",
        ["analysis_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_sentiment_collected_post_id"),
        "ticker_sentiment",
        ["collected_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_sentiment_id"), "ticker_sentiment", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ticker_sentiment_ticker"), "ticker_sentiment", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_sentiment_ticker"), table_name="ticker_sentiment")
    op.drop_index(op.f("ix_ticker_sentiment_id"), table_name="ticker_sentiment")
    op.drop_index(
        op.f("ix_ticker_sentiment_collected_post_id"), table_name="ticker_sentiment"
    )
    op.drop_index(
        op.f("ix_ticker_sentiment_analysis_result_id"), table_name="ticker_sentiment"
    )
    op.drop_table("ticker_sentiment")
    op.drop_index(
        op.f("ix_user_ticker_weights_weight_ratio"), table_name="user_ticker_weights"
    )
    op.drop_index(
        op.f("ix_user_ticker_weights_ticker"), table_name="user_ticker_weights"
    )
    op.drop_index(
        op.f("ix_user_ticker_weights_account_id"), table_name="user_ticker_weights"
    )
    op.drop_table("user_ticker_weights")
    op.drop_index(
        op.f("ix_stock_ticker_map_company_name"), table_name="stock_ticker_map"
    )
    op.drop_table("stock_ticker_map")
    # ### end Alembic commands ###
